import Head from 'next/head';
import {StartSection, SkillSection, StepSection} from '../components';
import styles from '../styles/home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>SkillyTree</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.sections}>
				<StartSection />
				<SkillSection />
				<StepSection />
			</div>
		</div>
	);
}
