import styles from '../styles/dashboard.module.css';
import {Journey} from '../components';
import Head from 'next/head';

function MyLessons ({className}) {
  return (
    <section className={`${styles.container} ${className}`}>
      <Head>
				<title>MyLessons</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
      <h1 className={styles.title}>Start Your Journey Now</h1>
      <div className={styles.content}>
        <Journey />
      </div>
    </section>
  )
}

export default MyLessons;